parallel-jobs = 1

[YouTube]
enabled = false 
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
enable-magisk-update = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music]
enabled = false 
app-name = "Music"
build-mode = "both"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
enable-magisk-update = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Photos]
enabled = false
app-name = "Photos"
build-mode = "both"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
enable-magisk-update = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
enable-magisk-update = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music-Extended]
enabled = false
app-name = "Music"
build-mode = "both"
arch = "both"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
enable-magisk-update = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Reddit-Extended]
enabled = false
app-name = "Reddit"
build-mode = "apk"
arch = "both"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[YouTube-Anddea]
enabled = false
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
rv-brand = "ReVanced Anddea"
patches-source = "anddea/revanced-patches"
enable-magisk-update = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music-Anddea]
enabled = false
app-name = "Music"
build-mode = "both"
arch = "both"
version = "auto"
rv-brand = "ReVanced Anddea"
patches-source = "anddea/revanced-patches"
enable-magisk-update = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Reddit-Anddea]
enabled = false
app-name = "Reddit"
build-mode = "apk"
arch = "both"
version = "auto"
rv-brand = "ReVanced Anddea"
patches-source = "anddea/revanced-patches"
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Spotify-Anddea]
enabled = true
app-name = "Spotify"
build-mode = "apk"
arch = "both"
version = "auto"
rv-brand = "ReVanced Anddea"
patches-source = "anddea/revanced-patches"
# dpi = "320-640dpi"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

