parallel-jobs = 1
remove-rv-integrations-checks = true

[Photos]
enabled = true
app-name = "Photos"
build-mode = "apk"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
