parallel-jobs = 1
enable-magisk-update = true
remove-rv-integrations-checks = true

[TikTok]
enabled = true 
app-name = "TikTok"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
# dpi = "120-640dpi"
apkmirror-dlurl = "apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
uptodown-dlurl = "tiktok.en.uptodown.com/android"

[Twitter]
enabled = true 
app-name = "Twitter"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
# dpi = "120-640dpi"
apkmirror-dlurl = "apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "twitter.en.uptodown.com/android"

[Lightroom]
enabled = true 
app-name = "Lightroom"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
apkmirror-dlurl = "apkmirror.com/apk/adobe/lightroom"
uptodown-dlurl = "adobe-lightroom-mobile.en.uptodown.com/android"

[Messenger]
enabled = true 
app-name = "Messenger"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
apkmirror-dlurl = "apkmirror.com/apk/facebook-2/messenger/"
uptodown-dlurl = "facebook-messenger.en.uptodown.com/android"


