# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

parallel-jobs = 1
remove-rv-integrations-checks = true

[Music-Anddea]
enabled = true
app-name = "Music"
build-mode = "apk"
# arch = "both"
version = "auto"
rv-brand = "ReVanced Anddea"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

