parallel-jobs = 1
enable-magisk-update = true
remove-rv-integrations-checks = true

[Photos]
enabled = true
app-name = "Photos"
build-mode = "both"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"


