parallel-jobs = 1
cli-source = "j-hc/revanced-cli"
remove-rv-integrations-checks = true

[Lightroom]
enabled = true
app-name = "Lightroom"
build-mode = "apk"
arch = "all"
version = "9.3.0"
patches-source = "revanced/revanced-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
