[Duolingo]
enabled = true
app-name = "Duolingo"
build-mode = "apk"
arch = "both"
version = "latest"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
remove-rv-integrations-checks = true
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
