parallel-jobs = 1
enable-magisk-update = true
remove-rv-integrations-checks = true

[Spotify-Anddea]
enabled = true
app-name = "Spotify"
build-mode = "apk"
rv-brand = "ReVanced Anddea"
patches-source = "anddea/revanced-patches"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Music]
enabled = true
app-name = "Music"
build-mode = "both"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[Reddit-Extended]
enabled = true
app-name = "Reddit"
build-mode = "apk"
arch = "both"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
