parallel-jobs = 1
enable-magisk-update = true
remove-rv-integrations-checks = true

[YouTube-Anddea]
enabled = true
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
rv-brand = "ReVanced Anddea"
patches-source = "anddea/revanced-patches"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
