parallel-jobs = 1
enable-magisk-update = true
remove-rv-integrations-checks = true

[Spotify-Anddea]
enabled = true
app-name = "Spotify"
build-mode = "apk"
arch = "arm64-v8a"
version = "latest"
rv-brand = "ReVanced Anddea"
patches-source = "anddea/revanced-patches"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
