[YouTube]
enabled = true
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
enable-magisk-update = true
remove-rv-integrations-checks = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
enabled = true
app-name = "Music"
build-mode = "both"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
enable-magisk-update = true
remove-rv-integrations-checks = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Photos]
enabled = true
app-name = "Photos"
build-mode = "both"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
enable-magisk-update = true
remove-rv-integrations-checks = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Spotify]
enabled = true
app-name = "Spotify"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
remove-rv-integrations-checks = true
# apkmirror-dpi = "480dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"

[Reddit]
enabled = true
app-name = "Reddit"
build-mode = "apk"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
remove-rv-integrations-checks = true
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Twitter]
enabled = true
app-name = "Twitter"
build-mode = "apk"
arch = "both"
version = "latest"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
remove-rv-integrations-checks = true
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[Twitch]
enabled = true
app-name = "Twitch"
build-mode = "apk"
arch = "both"
version = "latest"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
remove-rv-integrations-checks = true
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"

[Duolingo]
enabled = true
app-name = "Duolingo"
build-mode = "apk"
arch = "all"
version = "latest"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
remove-rv-integrations-checks = true
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"

[TikTok]
enabled = true
app-name = "TikTok"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
remove-rv-integrations-checks = true
# apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
cli-source = "j-hc/revanced-cli"
enable-magisk-update = true
remove-rv-integrations-checks = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Extended]
enabled = true
app-name = "Music"
build-mode = "both"
arch = "both"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
cli-source = "j-hc/revanced-cli"
enable-magisk-update = true
remove-rv-integrations-checks = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Reddit-Extended]
enabled = true
app-name = "Reddit"
build-mode = "apk"
arch = "both"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
cli-source = "j-hc/revanced-cli"
remove-rv-integrations-checks = true
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[YouTube-Anddea]
enabled = false
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
rv-brand = "ReVanced Anddea"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
enable-magisk-update = true
remove-rv-integrations-checks = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Anddea]
enabled = false
app-name = "Music"
build-mode = "both"
arch = "both"
version = "auto"
rv-brand = "ReVanced Anddea"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
enable-magisk-update = true
remove-rv-integrations-checks = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Spotify-Anddea]
enabled = false
app-name = "Spotify"
build-mode = "apk"
arch = "all"
version = "latest"
rv-brand = "ReVanced Anddea"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
remove-rv-integrations-checks = true
# apkmirror-dpi = "480dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"

[Reddit-Anddea]
enabled = false
app-name = "Reddit"
build-mode = "apk"
arch = "both"
version = "auto"
rv-brand = "ReVanced Anddea"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
remove-rv-integrations-checks = true
apkmirror-dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"




