patches-version = "dev"
parallel-jobs = 1
enable-magisk-update = true
remove-rv-integrations-checks = true

[YouTube]
enabled = false
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
apkmirror-dlurl = "apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "youtube.en.uptodown.com/android"

[Music]
enabled = false
app-name = "Music"
build-mode = "both"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
apkmirror-dlurl = "apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "youtube-music.en.uptodown.com/android"

[Photos]
enabled = false
app-name = "Photos"
build-mode = "both"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
apkmirror-dlurl = "apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "google-photos.en.uptodown.com/android"

[Duolingo]
enabled = false 
app-name = "Duolingo"
build-mode = "apk"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
dpi = "120-640dpi"
apkmirror-dlurl = "apkmirror.com/apk/duolingo/duolingo-duolingo"
uptodown-dlurl = "duolingo.en.uptodown.com/android"

[Twitch]
enabled = false 
app-name = "Twitch"
build-mode = "apk"
arch = "all"
version = "25.3.0"
patches-source = "revanced/revanced-patches"
dpi = "120-640dpi"
apkmirror-dlurl = "apkmirror.com/apk/twitch-interactive-inc/twitch"
uptodown-dlurl = "twitch.en.uptodown.com/android"

[ProtonMail]
enabled = false 
app-name = "ProtonMail"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
apkmirror-dlurl = "apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
uptodown-dlurl = "protonmail.en.uptodown.com/android"

[SamsungRadio]
enabled = false 
app-name = "SamsungRadio"
build-mode = "apk"
arch = "both"
version = "auto"
patches-source = "revanced/revanced-patches"
apkmirror-dlurl = "apkmirror.com/apk/samsung-electronics-co-ltd/samsung-radio/"
uptodown-dlurl = "samsung-radio.en.uptodown.com/android"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
apkmirror-dlurl = "apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "youtube.en.uptodown.com/android"

[Music-Extended]
enabled = true
app-name = "Music"
build-mode = "both"
arch = "both"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
apkmirror-dlurl = "apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "youtube-music.en.uptodown.com/android"

[Reddit-Extended]
enabled = true
app-name = "Reddit"
build-mode = "apk"
arch = "both"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "inotia00/revanced-patches"
dpi = "120-640dpi"
apkmirror-dlurl = "apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "reddit-official-app.en.uptodown.com/android"

[YouTube-Advanced]
enabled = false
app-name = "YouTube"
build-mode = "both"
arch = "all"
version = "auto"
rv-brand = "ReVanced Advanced"
patches-source = "anddea/revanced-patches"
apkmirror-dlurl = "apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "youtube.en.uptodown.com/android"

[Music-Advanced]
enabled = false
app-name = "Music"
build-mode = "both"
arch = "both"
version = "auto"
rv-brand = "ReVanced Advanced"
patches-source = "anddea/revanced-patches"
apkmirror-dlurl = "apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "youtube-music.en.uptodown.com/android"

[Reddit-Advanced]
enabled = false
app-name = "Reddit"
build-mode = "apk"
arch = "both"
version = "auto"
rv-brand = "ReVanced Advanced"
patches-source = "anddea/revanced-patches"
dpi = "120-640dpi"
apkmirror-dlurl = "apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "reddit-official-app.en.uptodown.com/android"



