parallel-jobs = 1
enable-magisk-update = true
remove-rv-integrations-checks = true

[TikTok]
enabled = true 
app-name = "TikTok"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
uptodown-dlurl = "tiktok.en.uptodown.com/android"

[Twitter]
enabled = true 
app-name = "Twitter"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
uptodown-dlurl = "twitter.en.uptodown.com/android"

[Lightroom]
enabled = true 
app-name = "Lightroom"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
uptodown-dlurl = "adobe-lightroom-mobile.en.uptodown.com/android"

[Messenger]
enabled = true 
app-name = "Messenger"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
uptodown-dlurl = "facebook-messenger.en.uptodown.com/android"


