name: Delete Releases and Workflows

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete older releases and workflows
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          delete_tags: true
          releases_keep_latest: 10
          delete_workflows: true
          workflows_keep_day: 1
          gh_token: ${{ secrets.GITHUB_TOKEN }}
